# Generated by Django 5.0.6 on 2024-06-24 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrongPointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'strong point',
                'verbose_name_plural': 'strong points',
                'indexes': [models.Index(fields=['user_id'], name='strong_point_user_id_idx'), models.Index(fields=['id'], name='strong_point_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user action',
                'verbose_name_plural': 'user actions',
                'indexes': [models.Index(fields=['user_id'], name='user_action_user_id_idx'), models.Index(fields=['id'], name='user_action_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeakPointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weakness', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'weak point',
                'verbose_name_plural': 'weak points',
                'indexes': [models.Index(fields=['user_id'], name='weak_point_user_id_idx'), models.Index(fields=['id'], name='weak_point_id_idx')],
            },
        ),
    ]
